version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ATBD
    ports:
        - 8000:8000
    volumes:
      - ./ATBD/:/usr/src/ATBD/
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prasad@123
      - POSTGRES_DB=covidbooth

volumes:
  postgres_data: